version: '3'

services:
  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bookmarkers
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5432:5432'
    volumes:
      - ./sql/bookmarks.sql:/docker-entrypoint-initdb.d/bookmarks.sql # initial data
      - postgres_data:/var/lib/postgresql/data # Mount named volume for persistence

volumes:
  postgres_data: # Declare named volume for persistence
