CREATE TABLE IF NOT EXISTS public.tokens (
	id SERIAL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	access_token TEXT NOT NULL,
	refresh_token TEXT NOT NULL,
	expiry_date TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
)
